### ISSUE TITLE
Logging Line number of a Error

### ISSUE THREAD

**Issue by amoghh** [ridiculous/grape-middleware-logger#26]
Hi we are using Rails 4 and Grape on our production and i was wondering if there was any way or a an option to Log the the line number the way how nginx logs. It is becoming problem for us to debug when there are code errors in our API and takes a lot of trial and error to determine which line could have caused it.

**Comment by ridiculous** [comment]
In the case of `after_exception` we could potentially log the first line of the backtrace. Is that what you're asking? Are you using an error tracking service to notify you of errors? Like Airbrake or Honeybadger? That's really what I would be using to log errors, instead of looking thru your own log files. And really, in the case of an exception, the whole backtrace should be logged.
